import streamlit as st
from google import genai
from google.genai import types
from PIL import Image
import io

# --- 1. PAGE SETUP ---
st.set_page_config(page_title="TahaGpt Super App", page_icon="🚀", layout="wide")

# --- 2. API CLIENT (2026 STABLE) ---
if "GEMINI_API_KEY" not in st.secrets:
    st.error("⚠️ Add GEMINI_API_KEY to Streamlit Secrets!")
    st.stop()

# This uses the latest stable 2026 SDK
client = genai.Client(api_key=st.secrets["GEMINI_API_KEY"])

# --- 3. SIDEBAR UI ---
with st.sidebar:
    st.title("🤖 TahaGpt Menu")
    
    # THE "+" ICON
    if st.button("➕ New Chat", use_container_width=True):
        st.session_state.messages = []
        st.rerun()
    
    st.divider()
    app_mode = st.radio("Select Tool:", ["💬 Chatbot", "🎨 Pic Generate", "🖼️ Analyze Image"])
    st.info("Home WiFi Version | Karachi 2026")

# --- 4. SESSION STATE ---
if "messages" not in st.session_state:
    st.session_state.messages = []

# --- 5. MODES ---

# --- MODE 1: CHATBOT ---
if app_mode == "💬 Chatbot":
    st.header("💬 Smart Chat")
    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    if prompt := st.chat_input("Ask TahaGpt anything..."):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        try:
            # FIX: Using the 2026 Stable Model Name
            response = client.models.generate_content(
                model="gemini-2.5-flash", 
                contents=prompt
            )
            with st.chat_message("assistant"):
                st.markdown(response.text)
            st.session_state.messages.append({"role": "assistant", "content": response.text})
        except Exception as e:
            st.error(f"Chat Error: {e}")

# --- MODE 2: PIC GENERATE ---
elif app_mode == "🎨 Pic Generate":
    st.header("🎨 AI Image Creator")
    user_prompt = st.text_area("Describe the picture you want:")
    
    if st.button("✨ Generate Picture"):
        with st.spinner("TahaGpt is drawing..."):
            try:
                # Using the latest Nano Banana 2 (Gemini 2.5 Flash Image)
                response = client.models.generate_content(
                    model='gemini-2.5-flash-image',
                    contents=user_prompt,
                    config=types.GenerateContentConfig(response_modalities=["IMAGE"])
                )
                for part in response.candidates[0].content.parts:
                    if part.inline_data:
                        img = Image.open(io.BytesIO(part.inline_data.data))
                        st.image(img, caption="Generated by TahaGpt", use_container_width=True)
            except Exception as e:
                st.error(f"Image Error: {e}")

# --- MODE 3: ANALYZE IMAGE ---
elif app_mode == "🖼️ Analyze Image":
    st.header("🖼️ Image Intelligence")
    uploaded_file = st.file_uploader("Upload a photo", type=['png', 'jpg', 'jpeg'])
    
    if uploaded_file:
        img = Image.open(uploaded_file)
        st.image(img, use_container_width=True)
        if st.button("🔍 Analyze"):
            try:
                # Stable multimodal model
                res = client.models.generate_content(
                    model="gemini-2.5-flash", 
                    contents=["Describe this image:", img]
                )
                st.write(res.text)
            except Exception as e:
                st.error(f"Analysis Error: {e}")
