import streamlit as st
from google import genai
from google.genai import types
from PIL import Image
import io

# --- PAGE SETUP ---
st.set_page_config(page_title="TahaGpt Super App", page_icon="🚀", layout="wide")

# --- API CLIENT ---
if "GEMINI_API_KEY" not in st.secrets:
    st.error("Please add GEMINI_API_KEY to your Streamlit Secrets!")
    st.stop()

client = genai.Client(api_key=st.secrets["GEMINI_API_KEY"])

# --- SIDEBAR (The "+" Icon is here!) ---
with st.sidebar:
    st.title("⚙️ TahaGpt Menu")
    if st.button("➕ New Chat"):
        st.session_state.messages = []
        st.rerun()
    
    st.divider()
    app_mode = st.radio("Select Tool:", ["💬 Chatbot", "🎨 Image Generator", "🖼️ Analyze Image"])
    st.info("Version 2026 | Karachi, Pakistan")

# --- INITIALIZE SESSION ---
if "messages" not in st.session_state:
    st.session_state.messages = []

# --- MODE 1: CHATBOT ---
if app_mode == "💬 Chatbot":
    st.header("💬 AI Conversation")
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    if prompt := st.chat_input("How can I help you today?"):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        # Using the standard Gemini 3 model for text
        response = client.models.generate_content(model="gemini-3.1-flash", contents=prompt)
        
        with st.chat_message("assistant"):
            st.markdown(response.text)
        st.session_state.messages.append({"role": "assistant", "content": response.text})

# --- MODE 2: IMAGE GENERATOR (Pic Generate) ---
elif app_mode == "🎨 Image Generator":
    st.header("🎨 AI Image Creator")
    prompt = st.text_area("Describe the picture you want to create:", placeholder="A futuristic robot playing cricket in Karachi...")
    
    if st.button("Generate Picture"):
        with st.spinner("Creating your masterpiece..."):
            try:
                # Using Nano Banana 2 for high-speed image generation
                response = client.models.generate_content(
                    model='gemini-3.1-flash-image',
                    contents=prompt,
                    config=types.GenerateContentConfig(response_modalities=["IMAGE"])
                )
                
                for part in response.candidates[0].content.parts:
                    if part.inline_data:
                        img = Image.open(io.BytesIO(part.inline_data.data))
                        st.image(img, caption="Generated by TahaGpt", use_container_width=True)
            except Exception as e:
                st.error(f"Generation failed: {e}")

# --- MODE 3: IMAGE ANALYSIS (See Photo) ---
elif app_mode == "🖼️ Analyze Image":
    st.header("🖼️ Image Intelligence")
    uploaded_file = st.file_uploader("Upload a photo", type=['png', 'jpg', 'jpeg'])
    
    if uploaded_file:
        img = Image.open(uploaded_file)
        st.image(img, caption="Uploaded Image", use_container_width=True)
        
        user_query = st.text_input("What do you want to know about this photo?", "Describe this image in detail")
        
        if st.button("Analyze Image"):
            with st.spinner("Analyzing..."):
                response = client.models.generate_content(
                    model="gemini-3.1-flash",
                    contents=[user_query, img]
                )
                st.write("### AI Analysis:")
                st.write(response.text)
